# Generated by Django 5.2 on 2025-05-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='reject_reason',
        ),
        migrations.AddField(
            model_name='campaign',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Reason for Approval/Rejection'),
        ),
    ]
